AllCops:
  TargetRubyVersion: 1.9

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

